blueprint:
  name: iluminize ZG2819S-RGBW
  description: Control lights with a iluminize 511.344 RGBW Remote
  domain: automation
  input:
    remote:
      name: 'Remote'
      description: iluminize 511.344 remote to use
      selector:
        device:
          integration: 'zha'
          manufacturer: 'Sunricher'
